version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build: ./API
    ports:
      - "4000:4000"

    depends_on:
      - db
    env_file:
      - ./API/.env
  web:
    build: ./web_interface
    ports:
      - "8081:8080"
